server:
  port: 8081

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level.root: info
  level.org.hibernate.SQL: info
  level.liquibase: info
  level.io.fdlessard.codebites.debezium.cdc.listener: DEBUG

spring:
  application:
    name: cdc-listener
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  kafka:
    bootstrap-servers: kafka-server:9092
  cloud:
    stream:
      bindings:
        customerChange-in-0:
          destination: dbserver1.public.customer
          group: customerListenerGroup
          contentType: application/json

        addressChange-in-0:
          destination: dbserver1.public.address
          group: addressListenerGroup
          contentType: application/json

    function:
      definition: customerChange;addressChange