version: '3.8'

networks:
  kafka-net:
    name: kafka-net

services:
  customer-api:
    build:
      context: './customer-api/'
      dockerfile: Dockerfile
    image: 'customer-api:0.0.1-SNAPSHOT'
    container_name: customer-api
    networks:
      - kafka-net
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: 'postgres:5432'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
    depends_on:
      - kafka-server
      - postgres
  customer-processor:
    build:
      context: './customer-processor/'
      dockerfile: Dockerfile
    image: 'customer-processor:0.0.1-SNAPSHOT'
    container_name: customer-processor
    networks:
      - kafka-net
    ports:
      - 8081:8080
    environment:
      WAIT_HOSTS: 'postgres:5432'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
    depends_on:
      - kafka-server
      - postgres
      - customer-api
  postgres:
    image: postgres:13.2
    container_name: spring-boot-cloud-stream-postgres
    hostname: postgres
    networks:
      - kafka-net
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    container_name: spring-boot-cloud-stream-zookeeper
    hostname: zookeeper-server
    networks:
      - kafka-net
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka-server:
    image: 'bitnami/kafka:latest'
    container_name: spring-boot-cloud-stream-kafka
    hostname: kafka-server
    networks:
      - kafka-net
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper-server