logging:
  level.root: INFO
  level.io.fdlessard.codebites.debezium.lambda: DEBUG

spring:
  application:
    name: lambda-cdc-listener
  output:
    ansi:
      enabled: always
  sql:
    init:
      platform: postgres
      mode: never
  datasource:
    username:
    password:
    driverClassName: org.postgresql.Driver
    url:
